[db]
  data-source = "postgresql://postgres.teivpvtmxjzpwrpzmhxf:Hinokamikagura1@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
  prepare-stmt = true
  log-level = 1
  [db.pool]
    enable = true
    max-idle-connections = 25
    max-lifetime = "10m"
    max-open-connections = 25

[cronjobs]
  enable = true

[jwt]
  allowed-users = [""]
  secret = "e66425a18474843ecda9587d90bd486df04acec0f731c04c78279f8ef32c2920"
  session-time = "30d"

[log]
  development = true
  level = -1

[server]
  graceful-shutdown = "15s"
  port = 8080
  read-timeout = "1h"
  write-timeout = "1h"

[tg]
  app-hash = "eae31c3d216d33d29a2212d5d209620b"
  app-id = 19066135
  app-version = "4.6.3 K"
  bg-bots-limit = 12
  device-model = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"
  disable-stream-bots = false
  lang-code = "en"
  lang-pack = "webk"
  rate = 50
  rate-burst = 20
  rate-limit = false
  session-file = ""
  system-lang-code = "en-US"
  system-version = "Win32"
  
  [tg.uploads]
    encryption-key = ""
    retention = "7d"
    threads = 8
  [tg.stream]
    multi-threads = 8
    buffers = 16

