services:
  - name: teldrive
    type: web
    env: docker
    dockerImage: ghcr.io/tgdrive/teldrive
    plan: free
    healthCheckPath: "/"
    ports:
      - port: 8080
    mounts:
      - path: /config.toml
        volumeName: config-file
      - path: /session.db
        volumeName: session-db

volumes:
  - name: config-file
    hostPath: ./config.toml
  - name: session-db
    hostPath: ./session.db
